// Products
export const FETCH_CATALOG_PRODUCTS_REQUEST = 'FETCH_CATALOG_PRODUCTS_REQUEST';
export const FETCH_CATALOG_PRODUCTS_SUCCESS = 'FETCH_CATALOG_PRODUCTS_SUCCESS';
export const FETCH_CATALOG_PRODUCTS_FAILURE = 'FETCH_CATALOG_PRODUCTS_FAILURE';
export const FETCH_CATALOG_FAVOURITES = 'FETCH_CATALOG_FAVOURITES';
export const FETCH_CATALOG_WATCHED = 'FETCH_CATALOG_WATCHED';
export const UPDATE_CATALOG_SORTING = 'UPDATE_CATALOG_SORTING';
export const UPDATE_ITEMS_PER_PAGE = 'UPDATE_ITEMS_PER_PAGE';

// Filters
export const FETCH_CATALOG_FILTERS_REQUEST = 'FETCH_CATALOG_FILTERS_REQUEST';
export const FETCH_CATALOG_FILTERS_SUCCESS = 'FETCH_CATALOG_FILTERS_SUCCESS';
export const FETCH_CATALOG_FILTERS_FAILURE = 'FETCH_CATALOG_FILTERS_FAILURE';
export const UPDATE_CATALOG_FILTERS = 'UPDATE_CATALOG_FILTERS';
export const RESET_ACTIVE_FILTERS = 'RESET_ACTIVE_FILTERS';

// User
export const ADD_TO_WATCHED_LIST = 'ADD_TO_WATCHED_LIST';
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_UPDATE = 'USER_UPDATE';

// Shopping Cart
export const SHOPPING_CART_UPDATE = 'SHOPPING_CART_UPDATE';
export const SHOPPING_CART_CLEAR = 'SHOPPING_CART_CLEAR';
